
Starting plotting progress into temporary dirs: /data-l/varvara/tmp and /data-l/varvara/tmp
ID: 08392fba197428cc3fddde17f489792cdf583079ba7a548fa43e0a690f47fa6b
Plot size is: 27
Buffer size is: 4096MiB
Using 16 buckets
Final Directory is: /data-l/varvara/plot
Using 1 threads of stripe size 1024
Process ID is: 754109

Starting phase 1/4: Forward Propagation into tmp files... Wed Jan  8 04:32:01 2025
Computing table 1
Progress update: 0.01
F1 complete, time: 4.233 seconds. CPU (99.95%) Wed Jan  8 04:32:06 2025
Computing table 2
Progress update: 0.06
	Bucket 0 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 1 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 2 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 3 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 4 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 5 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 6 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 7 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 8 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 9 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 10 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 11 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 12 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 13 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Bucket 14 uniform sort. Ram: 3.946GiB, u_sort min: 0.250GiB, qs min: 0.063GiB.
	Bucket 15 uniform sort. Ram: 3.946GiB, u_sort min: 0.125GiB, qs min: 0.062GiB.
	Total matches: 134190710
Caught plotting error: Matches do not match with number of write entries 134190710 134189128
Traceback (most recent call last):
  File "/data-l/varvara/chia-blockchain/.venv/bin/chia", line 6, in <module>
    sys.exit(main())
  File "/data-l/varvara/chia-blockchain/chia/cmds/chia.py", line 139, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data-l/varvara/chia-blockchain/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data-l/varvara/chia-blockchain/chia/cmds/plotters.py", line 17, in plotters_cmd
    call_plotters(ctx.obj["root_path"], args)
  File "/data-l/varvara/chia-blockchain/chia/plotters/plotters.py", line 541, in call_plotters
    plot_chia(args, chia_root_path)
  File "/data-l/varvara/chia-blockchain/chia/plotters/chiapos.py", line 58, in plot_chia
    asyncio.run(create_plots(params, plot_keys))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data-l/varvara/chia-blockchain/chia/plotting/create_plots.py", line 241, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
